# Generated by Django 4.2.1 on 2023-05-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nni", models.CharField(max_length=10)),
                ("nom", models.CharField(max_length=55)),
                ("localisation", models.CharField(max_length=55)),
                ("email", models.EmailField(max_length=32)),
                ("telephone", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Actif", "Actif"), ("NonActif", "NonActif")],
                        max_length=32,
                    ),
                ),
                ("typeCarburant", models.CharField(max_length=100)),
                ("modePaiyement", models.CharField(max_length=100)),
            ],
        ),
    ]
