# Generated by Django 4.2.1 on 2023-06-25 18:01

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=55)),
                ('localisation', models.CharField(max_length=55)),
                ('nni', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=32)),
                ('telephone', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('NonActif', 'NonActif')], max_length=32)),
                ('typeCarburant', models.CharField(max_length=100)),
                ('modePaiyement', models.CharField(max_length=100)),
                ('latitude', models.CharField(default='18.0858')),
                ('longitude', models.CharField(default='-15.9785')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='id', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
